
lane :updatepod do |options|
tagNum = options[:tag]
podspecName = options[:specName]\


# 3、提交本地仓库代码至远程仓库
git_add(path: ".")
git_commit(path: ".", message: "upgrade repo")
push_to_git_remote


# 4、打标签，并提交至远程
# 先验证tag是否存在，如果存在则删除本地标签和远程标签
if git_tag_exists(tag: tagNum)
  UI.message("您输入的tag:#{tagNum}已存在，即将自动清除") 
  remove_git_tag(tagNum: tagNum)
end
add_git_tag(
  tag: tagNum
)
push_git_tags


end